<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Credentials Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            line-height: 1.3;
            color: #333;
            margin: 0;
            padding: 15px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #2563eb;
            font-size: 18px;
            margin: 0;
        }
        .meta-info {
            background: #f8fafc;
            padding: 10px;
            border-radius: 6px;
            margin-bottom: 15px;
            border-left: 4px solid #2563eb;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 12px;
            margin-bottom: 15px;
        }
        .stat-card {
            background: #ffffff;
            border: 1px solid #e5e7eb;
            border-radius: 6px;
            padding: 10px;
            text-align: center;
        }
        .stat-number {
            font-size: 18px;
            font-weight: bold;
            color: #2563eb;
            display: block;
        }
        .stat-label {
            color: #6b7280;
            font-size: 9px;
            margin-top: 2px;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            font-size: 9px;
        }
        .table th,
        .table td {
            border: 1px solid #e5e7eb;
            padding: 4px;
            text-align: left;
        }
        .table th {
            background: #f9fafb;
            font-weight: bold;
            color: #374151;
        }
        .table tr:nth-child(even) {
            background: #f9fafb;
        }
        .section {
            margin-bottom: 20px;
        }
        .section h2 {
            color: #1f2937;
            font-size: 14px;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 5px;
            margin-bottom: 10px;
        }
        .footer {
            border-top: 1px solid #e5e7eb;
            padding-top: 10px;
            margin-top: 20px;
            text-align: center;
            color: #6b7280;
            font-size: 8px;
        }
        .type-badge {
            padding: 1px 4px;
            border-radius: 8px;
            font-size: 8px;
            font-weight: bold;
        }
        .type-degree { background: #dbeafe; color: #1e40af; }
        .type-certificate { background: #dcfce7; color: #166534; }
        .type-diploma { background: #fef3c7; color: #92400e; }
        .verification-code {
            font-family: 'Courier New', monospace;
            font-size: 8px;
            background: #f3f4f6;
            padding: 1px 3px;
            border-radius: 3px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>CREDENTIALS REPORT</h1>
        <div class="subtitle">Complete Credentials Directory & Analytics</div>
    </div>

    <div class="meta-info">
        <strong>Generated:</strong> {{ $generated_at->format('F j, Y \a\t g:i A') }}<br>
        <strong>Generated By:</strong> {{ $generated_by }}<br>
        <strong>Total Credentials:</strong> {{ number_format($total_credentials) }}
    </div>

    <div class="section">
        <h2>Credentials Statistics Overview</h2>
        <div class="stats-grid">
            <div class="stat-card">
                <span class="stat-number">{{ number_format($total_credentials) }}</span>
                <div class="stat-label">Total Credentials</div>
            </div>
            @foreach($credentials_by_type as $type => $count)
            <div class="stat-card">
                <span class="stat-number">{{ number_format($count) }}</span>
                <div class="stat-label">{{ $type }}s</div>
            </div>
            @endforeach
        </div>
    </div>

    <div class="section">
        <h2>Credentials by Institution</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Institution</th>
                    <th>Credentials Issued</th>
                    <th>Percentage</th>
                </tr>
            </thead>
            <tbody>
                @foreach($credentials_by_institution as $institution => $count)
                <tr>
                    <td>{{ $institution }}</td>
                    <td>{{ number_format($count) }}</td>
                    <td>{{ number_format(($count / $total_credentials) * 100, 1) }}%</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>All Credentials Directory</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Student</th>
                    <th>Credential Name</th>
                    <th>Type</th>
                    <th>Institution</th>
                    <th>Issued By</th>
                    <th>Issued Date</th>
                    <th>Verification Code</th>
                </tr>
            </thead>
            <tbody>
                @foreach($credentials as $credential)
                <tr>
                    <td>{{ $credential->student_first_name }} {{ $credential->student_last_name }}</td>
                    <td>{{ $credential->credential_name }}</td>
                    <td>
                        <span class="type-badge type-{{ strtolower($credential->type) }}">
                            {{ $credential->type }}
                        </span>
                    </td>
                    <td>{{ $credential->institution->name ?? 'N/A' }}</td>
                    <td>{{ $credential->issuedBy->first_name ?? 'N/A' }} {{ $credential->issuedBy->last_name ?? '' }}</td>
                    <td>{{ $credential->issued_at->format('M j, Y') }}</td>
                    <td><span class="verification-code">{{ $credential->verification_code }}</span></td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Recent Credential Activity</h2>
        <p><strong>Credentials Issued (Last 30 Days):</strong> {{ number_format($recent_credentials) }}</p>
        
        @if($recent_credentials > 0)
        <table class="table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Student</th>
                    <th>Credential</th>
                    <th>Type</th>
                    <th>Institution</th>
                </tr>
            </thead>
            <tbody>
                @foreach($credentials->where('issued_at', '>=', now()->subDays(30))->take(25) as $credential)
                <tr>
                    <td>{{ $credential->issued_at->format('M j') }}</td>
                    <td>{{ $credential->student_first_name }} {{ $credential->student_last_name }}</td>
                    <td>{{ $credential->credential_name }}</td>
                    <td>
                        <span class="type-badge type-{{ strtolower($credential->type) }}">
                            {{ $credential->type }}
                        </span>
                    </td>
                    <td>{{ $credential->institution->name ?? 'N/A' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @endif
    </div>

    <div class="footer">
        <p>This report contains official credential information and should be handled securely.</p>
        <p>Generated by Credify System | Report ID: {{ md5($generated_at . $generated_by) }}</p>
    </div>
</body>
</html>
