<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>System Audit Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #2563eb;
            font-size: 24px;
            margin: 0;
        }
        .header .subtitle {
            color: #6b7280;
            font-size: 14px;
            margin-top: 5px;
        }
        .meta-info {
            background: #f8fafc;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 25px;
            border-left: 4px solid #2563eb;
        }
        .section {
            margin-bottom: 30px;
        }
        .section h2 {
            color: #1f2937;
            font-size: 18px;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 8px;
            margin-bottom: 15px;
        }
        .section h3 {
            color: #374151;
            font-size: 14px;
            margin-bottom: 10px;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
            margin-bottom: 20px;
        }
        .stat-card {
            background: #ffffff;
            border: 1px solid #e5e7eb;
            border-radius: 6px;
            padding: 15px;
            text-align: center;
        }
        .stat-number {
            font-size: 28px;
            font-weight: bold;
            color: #2563eb;
            display: block;
        }
        .stat-label {
            color: #6b7280;
            font-size: 12px;
            margin-top: 5px;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .table th,
        .table td {
            border: 1px solid #e5e7eb;
            padding: 8px;
            text-align: left;
        }
        .table th {
            background: #f9fafb;
            font-weight: bold;
            color: #374151;
        }
        .table tr:nth-child(even) {
            background: #f9fafb;
        }
        .chart-placeholder {
            background: #f3f4f6;
            height: 200px;
            border-radius: 6px;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #6b7280;
            margin-bottom: 20px;
        }
        .footer {
            border-top: 1px solid #e5e7eb;
            padding-top: 20px;
            margin-top: 40px;
            text-align: center;
            color: #6b7280;
            font-size: 10px;
        }
        .highlight {
            background: #fef3c7;
            padding: 2px 6px;
            border-radius: 4px;
        }
        .text-success { color: #059669; }
        .text-warning { color: #d97706; }
        .text-danger { color: #dc2626; }
    </style>
</head>
<body>
    <div class="header">
        <h1>CREDIFY SYSTEM AUDIT REPORT</h1>
        <div class="subtitle">Comprehensive System Analysis & Statistics</div>
    </div>

    <div class="meta-info">
        <strong>Report Generated:</strong> {{ $generated_at->format('F j, Y \a\t g:i A') }}<br>
        <strong>Generated By:</strong> {{ $generated_by }}<br>
        <strong>Report Period:</strong> {{ $report_period['from'] }} to {{ $report_period['to'] }}<br>
        <strong>System Status:</strong> <span class="text-success">Operational</span>
    </div>

    <!-- System Overview -->
    <div class="section">
        <h2>System Overview</h2>
        <div class="stats-grid">
            <div class="stat-card">
                <span class="stat-number">{{ number_format($total_users) }}</span>
                <div class="stat-label">Total Users</div>
            </div>
            <div class="stat-card">
                <span class="stat-number">{{ number_format($total_credentials) }}</span>
                <div class="stat-label">Total Credentials</div>
            </div>
            <div class="stat-card">
                <span class="stat-number">{{ number_format($total_institutions) }}</span>
                <div class="stat-label">Total Institutions</div>
            </div>
            <div class="stat-card">
                <span class="stat-number">{{ number_format($recent_credentials) }}</span>
                <div class="stat-label">Credentials (Last 30 Days)</div>
            </div>
        </div>
    </div>

    <!-- User Statistics -->
    <div class="section">
        <h2>User Statistics</h2>
        <h3>Users by Role</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Role</th>
                    <th>Count</th>
                    <th>Percentage</th>
                </tr>
            </thead>
            <tbody>
                @foreach($users_by_role as $role => $count)
                <tr>
                    <td>{{ ucfirst(str_replace('_', ' ', $role)) }}</td>
                    <td>{{ number_format($count) }}</td>
                    <td>{{ number_format(($count / $total_users) * 100, 1) }}%</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <div class="stats-grid">
            <div class="stat-card">
                <span class="stat-number">{{ number_format($recent_users) }}</span>
                <div class="stat-label">New Users (Last 30 Days)</div>
            </div>
            <div class="stat-card">
                <span class="stat-number">{{ number_format($active_users) }}</span>
                <div class="stat-label">Active Users (Last 7 Days)</div>
            </div>
        </div>
    </div>

    <!-- Credential Statistics -->
    <div class="section">
        <h2>Credential Statistics</h2>
        <h3>Credentials by Type</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Count</th>
                    <th>Percentage</th>
                </tr>
            </thead>
            <tbody>
                @foreach($credentials_by_type as $type => $count)
                <tr>
                    <td>{{ $type }}</td>
                    <td>{{ number_format($count) }}</td>
                    <td>{{ number_format(($count / $total_credentials) * 100, 1) }}%</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <div class="stats-grid">
            <div class="stat-card">
                <span class="stat-number">{{ number_format($credentials_this_month) }}</span>
                <div class="stat-label">This Month</div>
            </div>
            <div class="stat-card">
                <span class="stat-number">{{ number_format($credentials_last_month) }}</span>
                <div class="stat-label">Last Month</div>
            </div>
        </div>
    </div>

    <!-- Institution Performance -->
    <div class="section">
        <h2>Institution Performance</h2>
        <h3>Top Institutions by Credentials Issued</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Institution</th>
                    <th>Credentials</th>
                    <th>Users</th>
                    <th>Avg. Credentials/User</th>
                </tr>
            </thead>
            <tbody>
                @foreach($top_institutions_by_credentials->take(10) as $institution)
                <tr>
                    <td>{{ $institution->name }}</td>
                    <td>{{ number_format($institution->credentials_count) }}</td>
                    <td>{{ number_format($institution->users_count) }}</td>
                    <td>{{ $institution->users_count > 0 ? number_format($institution->credentials_count / $institution->users_count, 1) : '0' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <div class="stats-grid">
            <div class="stat-card">
                <span class="stat-number">{{ number_format($institutions_with_credentials) }}</span>
                <div class="stat-label">Active Institutions</div>
            </div>
            <div class="stat-card">
                <span class="stat-number">{{ number_format($avg_credentials_per_institution, 1) }}</span>
                <div class="stat-label">Avg. Credentials/Institution</div>
            </div>
        </div>
    </div>

    <!-- Recent Activity -->
    <div class="section">
        <h2>Recent Activity</h2>
        <h3>Latest Credentials Issued</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Student</th>
                    <th>Credential</th>
                    <th>Institution</th>
                    <th>Type</th>
                </tr>
            </thead>
            <tbody>
                @foreach($recent_credentials_list->take(15) as $credential)
                <tr>
                    <td>{{ $credential->issued_at->format('M j, Y') }}</td>
                    <td>{{ $credential->student_first_name }} {{ $credential->student_last_name }}</td>
                    <td>{{ $credential->credential_name }}</td>
                    <td>{{ $credential->institution->name ?? 'N/A' }}</td>
                    <td>{{ $credential->type }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- System Health Indicators -->
    <div class="section">
        <h2>System Health Indicators</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Metric</th>
                    <th>Value</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>User Growth Rate (30 days)</td>
                    <td>{{ number_format($recent_users) }} new users</td>
                    <td><span class="text-success">Healthy</span></td>
                </tr>
                <tr>
                    <td>Credential Issuance Rate</td>
                    <td>{{ number_format($recent_credentials) }} in 30 days</td>
                    <td><span class="text-success">Active</span></td>
                </tr>
                <tr>
                    <td>Institution Participation</td>
                    <td>{{ number_format(($institutions_with_credentials / $total_institutions) * 100, 1) }}% active</td>
                    <td><span class="text-success">Good</span></td>
                </tr>
                <tr>
                    <td>System Utilization</td>
                    <td>{{ number_format(($active_users / $total_users) * 100, 1) }}% weekly active</td>
                    <td><span class="text-success">Engaged</span></td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="footer">
        <p>This report is confidential and intended for authorized personnel only.</p>
        <p>Generated by Credify System v1.0 | Report ID: {{ md5($generated_at . $generated_by) }}</p>
    </div>
</body>
</html>
