<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 11px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 15px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 15px;
            margin-bottom: 25px;
        }
        .header h1 {
            color: #2563eb;
            font-size: 20px;
            margin: 0;
        }
        .meta-info {
            background: #f8fafc;
            padding: 12px;
            border-radius: 6px;
            margin-bottom: 20px;
            border-left: 4px solid #2563eb;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 15px;
            margin-bottom: 20px;
        }
        .stat-card {
            background: #ffffff;
            border: 1px solid #e5e7eb;
            border-radius: 6px;
            padding: 12px;
            text-align: center;
        }
        .stat-number {
            font-size: 20px;
            font-weight: bold;
            color: #2563eb;
            display: block;
        }
        .stat-label {
            color: #6b7280;
            font-size: 10px;
            margin-top: 3px;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            font-size: 10px;
        }
        .table th,
        .table td {
            border: 1px solid #e5e7eb;
            padding: 6px;
            text-align: left;
        }
        .table th {
            background: #f9fafb;
            font-weight: bold;
            color: #374151;
        }
        .table tr:nth-child(even) {
            background: #f9fafb;
        }
        .section {
            margin-bottom: 25px;
        }
        .section h2 {
            color: #1f2937;
            font-size: 16px;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 6px;
            margin-bottom: 12px;
        }
        .footer {
            border-top: 1px solid #e5e7eb;
            padding-top: 15px;
            margin-top: 30px;
            text-align: center;
            color: #6b7280;
            font-size: 9px;
        }
        .role-badge {
            padding: 2px 6px;
            border-radius: 12px;
            font-size: 9px;
            font-weight: bold;
        }
        .role-super-admin { background: #fecaca; color: #991b1b; }
        .role-institutional-admin { background: #fed7aa; color: #9a3412; }
        .role-student { background: #bbf7d0; color: #166534; }
    </style>
</head>
<body>
    <div class="header">
        <h1>USERS REPORT</h1>
        <div class="subtitle">Complete User Directory & Statistics</div>
    </div>

    <div class="meta-info">
        <strong>Generated:</strong> {{ $generated_at->format('F j, Y \a\t g:i A') }}<br>
        <strong>Generated By:</strong> {{ $generated_by }}<br>
        <strong>Total Users:</strong> {{ number_format($total_users) }}
    </div>

    <div class="section">
        <h2>User Statistics Overview</h2>
        <div class="stats-grid">
            @foreach($users_by_role as $role => $count)
            <div class="stat-card">
                <span class="stat-number">{{ number_format($count) }}</span>
                <div class="stat-label">{{ ucfirst(str_replace('_', ' ', $role)) }}</div>
            </div>
            @endforeach
        </div>
    </div>

    <div class="section">
        <h2>All Users Directory</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>School ID</th>
                    <th>Role</th>
                    <th>Institution</th>
                    <th>Registered</th>
                    <th>Last Active</th>
                </tr>
            </thead>
            <tbody>
                @foreach($users as $user)
                <tr>
                    <td>{{ $user->first_name }} {{ $user->last_name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->school_id ?? 'N/A' }}</td>
                    <td>
                        <span class="role-badge role-{{ str_replace('_', '-', $user->role) }}">
                            {{ ucfirst(str_replace('_', ' ', $user->role)) }}
                        </span>
                    </td>
                    <td>{{ $user->institution->name ?? 'N/A' }}</td>
                    <td>{{ $user->created_at->format('M j, Y') }}</td>
                    <td>{{ $user->updated_at->format('M j, Y') }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Recent User Activity</h2>
        <p><strong>New Users (Last 30 Days):</strong> {{ number_format($recent_users) }}</p>
        
        @if($recent_users > 0)
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Institution</th>
                    <th>Registered</th>
                </tr>
            </thead>
            <tbody>
                @foreach($users->where('created_at', '>=', now()->subDays(30))->take(20) as $user)
                <tr>
                    <td>{{ $user->first_name }} {{ $user->last_name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>
                        <span class="role-badge role-{{ str_replace('_', '-', $user->role) }}">
                            {{ ucfirst(str_replace('_', ' ', $user->role)) }}
                        </span>
                    </td>
                    <td>{{ $user->institution->name ?? 'N/A' }}</td>
                    <td>{{ $user->created_at->format('M j, Y') }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @endif
    </div>

    <div class="footer">
        <p>This report contains sensitive user information and should be handled according to data protection policies.</p>
        <p>Generated by Credify System | Report ID: {{ md5($generated_at . $generated_by) }}</p>
    </div>
</body>
</html>
