<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Multiple Credentials Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 11px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #2563eb;
            font-size: 22px;
            margin: 0;
        }
        .meta-info {
            background: #f8fafc;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 25px;
            border-left: 4px solid #2563eb;
        }
        .credential-item {
            background: #ffffff;
            border: 1px solid #e5e7eb;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.05);
        }
        .credential-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 15px;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 10px;
        }
        .credential-name {
            font-size: 16px;
            font-weight: bold;
            color: #1f2937;
        }
        .credential-type {
            padding: 4px 10px;
            border-radius: 12px;
            font-size: 10px;
            font-weight: bold;
            text-transform: uppercase;
        }
        .type-degree { background: #dbeafe; color: #1e40af; }
        .type-certificate { background: #dcfce7; color: #166534; }
        .type-diploma { background: #fef3c7; color: #92400e; }
        .credential-details {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 15px;
        }
        .detail-row {
            display: flex;
            justify-content: space-between;
        }
        .detail-label {
            font-weight: bold;
            color: #374151;
        }
        .detail-value {
            color: #1f2937;
        }
        .verification-section {
            margin-top: 15px;
            padding: 10px;
            background: #f9fafb;
            border-radius: 6px;
            border: 1px solid #e5e7eb;
        }
        .verification-code {
            font-family: 'Courier New', monospace;
            font-size: 12px;
            font-weight: bold;
            background: #ffffff;
            padding: 6px 10px;
            border: 1px dashed #2563eb;
            border-radius: 4px;
            color: #2563eb;
            display: inline-block;
        }
        .footer {
            border-top: 1px solid #e5e7eb;
            padding-top: 15px;
            margin-top: 30px;
            text-align: center;
            color: #6b7280;
            font-size: 9px;
        }
        .page-break {
            page-break-before: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>CREDENTIALS BATCH REPORT</h1>
        <div class="subtitle">Multiple Credentials Export</div>
    </div>

    <div class="meta-info">
        <strong>Generated:</strong> {{ $generated_at->format('F j, Y \a\t g:i A') }}<br>
        <strong>Generated By:</strong> {{ $generated_by }}<br>
        <strong>Total Credentials:</strong> {{ number_format($total_credentials) }}
    </div>

    @foreach($credentials as $index => $credential)
        @if($index > 0 && $index % 2 == 0)
            <div class="page-break"></div>
        @endif
        
        <div class="credential-item">
            <div class="credential-header">
                <div class="credential-name">{{ $credential->credential_name }}</div>
                <span class="credential-type type-{{ strtolower($credential->type) }}">
                    {{ $credential->type }}
                </span>
            </div>
            
            <div class="credential-details">
                <div class="detail-row">
                    <span class="detail-label">Student:</span>
                    <span class="detail-value">{{ $credential->student_first_name }} {{ $credential->student_last_name }}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Student ID:</span>
                    <span class="detail-value">{{ $credential->student_school_id }}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Institution:</span>
                    <span class="detail-value">{{ $credential->institution->name ?? 'N/A' }}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Date Issued:</span>
                    <span class="detail-value">{{ $credential->issued_at->format('F j, Y') }}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Issued By:</span>
                    <span class="detail-value">{{ $credential->issuedBy->first_name ?? 'N/A' }} {{ $credential->issuedBy->last_name ?? '' }}</span>
                </div>
            </div>
            
            <div class="verification-section">
                <strong>Verification Code:</strong> 
                <span class="verification-code">{{ $credential->verification_code }}</span>
                <br><br>
                <strong>Verify at:</strong> {{ url("/verify/{$credential->id}") }}
                <br>
                <strong>Digital Hash:</strong> <span style="font-family: 'Courier New', monospace; font-size: 9px;">{{ substr($credential->credential_hash, 0, 32) }}...</span>
            </div>
        </div>
    @endforeach

    <div class="footer">
        <p><strong>This report contains official digital credentials and should be handled securely.</strong></p>
        <p>Generated by Credify System | All credentials are cryptographically verified</p>
    </div>
</body>
</html>
